exclude:
- README.md
- start.bat

gems:
  - jekyll-sitemap
  - jekyll-paginate

timezone: Europe/Berlin

title: WolframClient.net

mcversions:
  "1.11": "1.11 - 1.11.2"
  "1.10": "1.10 - 1.10.2"
  "1.9.4": "1.9.4"
  "1.8": "1.8 - 1.8.9"

paginate: 8
paginate_path: "/news/:num/"
permalink: /news/:year-:month-:day-:title/
excerpt_separator: <!--read more-->

analytics-id: UA-52838431-13

collections:
  redirects:
    output: true
    permalink: /:path/
  questions:
    output: true
    permalink: /faq/:slug/
  api:
    output: true
    permalink: /api/:path

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Alexander01998
      repo: Wolfram-MCX
  - scope:
      path: ""
      type: "redirects"
    values:
      layout: "redirect"
  - scope:
      path: ""
      type: questions
    values:
      layout: question
      category: Miscellaneous
  - scope:
      path: ""
      type: api
    values:
      layout: none
