exclude:
- /images
- README.md
- start.bat

gems:
  - jekyll-sitemap
  - jekyll-paginate

timezone: Europe/Berlin

title: Wolfram

paginate: 8
paginate_path: "/news/:num/"
permalink: /news/:year-:month-:day-:title/
excerpt_separator: <!--read more-->

analytics-id: UA-52838431-13

collections:
  contact:
    output: true
    permalink: /contact/:name/
  redirects:
    output: true
    permalink: /:path/
  questions:
    output: true
    permalink: /faq/:slug/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Alexander01998
  - scope:
      path: ""
      type: "contact"
    values:
      layout: contact
  - scope:
      path: ""
      type: "redirects"
    values:
      layout: "redirect"
  - scope:
      path: ""
      type: questions
    values:
      layout: question
      category: Miscellaneous
