exclude:
- /images
- README.md
- start.bat

gems:
  - jekyll-sitemap
  - jekyll-paginate

timezone: Europe/Berlin

title: Wolfram

analytics-id: UA-52838431-13

collections:
  redirects:
    output: true
    permalink: /:path/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "redirects"
    values:
      layout: "redirect"
